server:
  port: 8080

spring:
  application:
    name: trading

  # Database H2 (In-memory)
  datasource:
    url: jdbc:h2:mem:trading
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 console
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  # JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false # For debug
    hibernate:
      ddl-auto: update # Auto create tables
    properties:
      hibernate:
        format_sql: true

# Trading config
trading:
  fee-percent: 0.1
  min-order-value: 10.0

binance:
  api:
    url: https://api.binance.com/api/v3/ticker/bookTicker

huobi:
  api:
    url: https://api.huobi.pro/market/tickers